name: Initializing Database

on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  init-db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: THAKUR-ROHIT-21/banking-app-two-tier-deployment
          ref: main

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::306158389325:role/GitHub-action-deploy-role-policy
          aws-region: ap-south-1

      - name: Upload file on S3
        run: |
          aws s3 mb s3://306158389325-devops-scripts --region ap-south-1 2>/dev/null || true
          aws s3 cp init.sql s3://306158389325-devops-scripts/init.sql --region ap-south-1
          aws s3 cp init.py s3://306158389325-devops-scripts/init.py --region ap-south-1
          aws s3 ls s3://306158389325-devops-scripts/ --region ap-south-1
          echo "✅ Files Uploaded to bucket.."

      - name: Run init Test on Fleet
        id: init
        run: |
          CMD_ID=$(aws ssm send-command \
            --targets "Key=InstanceIds,Values=i-0a6833cb5c3c2bb0d" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "rm -f /home/ubuntu/init.py /home/ubuntu/init.sql",
              "aws s3 cp s3://306158389325-devops-scripts/init.py /home/ubuntu/init.py --region ap-south-1",
              "aws s3 cp s3://306158389325-devops-scripts/init.sql /home/ubuntu/init.sql --region ap-south-1",
              "ls -l /home/ubuntu/init.py /home/ubuntu/init.sql",
              "python3 -m pip install pymysql boto3 -q",
              "python3 /home/ubuntu/init.py",
              "rm -f /home/ubuntu/init.py /home/ubuntu/init.sql"
            ]}' \
            --query 'Command.CommandId' \
            --output text \
            --region ap-south-1)

          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT

      - name: Show Results
        run: |
          sleep 30

          aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --details \
            --region ap-south-1 \
            --output text

          FAILED=$(aws ssm list-command-invocations \
            --command-id "${{ steps.init.outputs.cmd_id }}" \
            --query "length(CommandInvocations[?Status=='Failed'])" \
            --output text \
            --region ap-south-1)

          if [ "$FAILED" -gt 0 ]; then
            echo "::error::init test failed on $FAILED instance(s)!"
            exit 1
          fi

          echo "✅ init Test Passed!"