name: Smoke testing for infra and networking

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      S3_BUCKET: 306158389325-devops-scripts
      SCRIPT_NAME: smoke_test.py

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::306158389325:role/GitHub-action-deploy-role-policy
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload smoke_test.py on AWS
        run: |
          aws s3 cp "$SCRIPT_NAME" \
            "s3://$S3_BUCKET/$SCRIPT_NAME" \
            --region "$AWS_REGION"

      - name: Run Smoke Test on Fleet
        id: smoke
        run: |
          CMD_ID=$(aws ssm send-command \
            --targets "Key=tag:App,Values=flask" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "aws s3 cp s3://306158389325-devops-scripts/smoke_test.py /tmp/smoke_test.py --region ap-south-1",
              "python3 /tmp/smoke_test.py",
              "rm -f /tmp/smoke_test.py"
            ]}' \
            --query 'Command.CommandId' \
            --output text \
            --region "$AWS_REGION")

          echo "cmd_id=$CMD_ID" >> "$GITHUB_OUTPUT"
          echo "Command ID: $CMD_ID"

      - name: Show Results
        run: |
          sleep 30

          aws ssm list-command-invocations \
            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
            --details \
            --region "$AWS_REGION" \
            --output text

          FAILED=$(aws ssm list-command-invocations \
            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
            --query "length(CommandInvocations[?Status=='Failed'])" \
            --output text \
            --region "$AWS_REGION")

          if [ "$FAILED" -gt 0 ]; then
            echo "::error::Health Check Failed on $FAILED instances"
            exit 1
          fi

          echo "Smoke Test Passed ✅"