name: Smoke testing for infra and networking

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::306158389325:role/GitHub-action-deploy-role-policy
          aws-region: ap-south-1

      - name: Create S3 bucket if not exists
        run: |
          BUCKET_NAME="306158389325-devops-scripts"
          REGION="ap-south-1"

          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket already exists ✅"
          else
            echo "Creating bucket..."
            aws s3api create-bucket \
              --bucket "$BUCKET_NAME" \
              --region "$REGION" \
              --create-bucket-configuration LocationConstraint="$REGION"
          fi

      - name: Upload smoke_test.py on AWS
        run: |
          aws s3 cp smoke_test.py \
            s3://306158389325-devops-scripts/smoke_test.py \
            --region ap-south-1

      - name: Run Smoke Test on Fleet
        id: smoke
        run: |
          CMD_ID=$(aws ssm send-command \
            --targets "Key=tag:App,Values=flask" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "aws s3 cp s3://306158389325-devops-scripts/smoke_test.py /tmp/smoke_test.py --region ap-south-1",
              "python3 /tmp/smoke_test.py",
              "rm -f /tmp/smoke_test.py"
            ]}' \
            --query 'Command.CommandId' \
            --output text \
            --region ap-south-1)

          echo "cmd_id=$CMD_ID" >> "$GITHUB_OUTPUT"
          echo "Command ID: $CMD_ID"

      - name: Show Results
        run: |
          sleep 30

          aws ssm list-command-invocations \
            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
            --details \
            --region ap-south-1 \
            --output text

          FAILED=$(aws ssm list-command-invocations \
            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
            --query "length(CommandInvocations[?Status=='Failed'])" \
            --output text \
            --region ap-south-1)

          if [ "$FAILED" -gt 0 ]; then
            echo "::error::Smoke Test Failed on $FAILED instance(s)"
            exit 1
          fi

          echo "Smoke Test Passed ✅"