name: Test Workflow

on:
  push:
    branches:
      - main
      - prod
      - dev

jobs:
  working-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Message
        run: echo "GitHub Action is Working Successfully ✅"